from django.urls import path
from . import views

urlpatterns = [
    path('courses/', views.get_courses, name='get_courses'),
    path('my-grades/', views.get_my_grades, name='get_my_grades'),
    path('upload-grades/', views.UploadGradesView.as_view(), name='upload_grades'),
    path('news/', views.get_news, name='get_news'),
    path('doctor/grades/', views.ManageGradesView.as_view(), name='doctor_grades'),
    path('doctor/grades/<int:pk>/update/', views.update_grade, name='update_grade'),
    path('my-attendance/', views.get_my_attendance, name='get_my_attendance'),
    path('upload-attendance/', views.UploadAttendanceView.as_view(), name='upload_attendance'),
    path('upload-material/', views.UploadMaterialView.as_view(), name='upload_material'),
    path('courses/<int:course_id>/materials/', views.get_course_materials, name='get_course_materials'),
    path('doctor/courses/', views.get_doctor_courses, name='get_doctor_courses'),
    path('material/<int:pk>/delete/', views.delete_material, name='delete_material'),
    path('departments/', views.DepartmentListCreateView.as_view(), name='department_list_create'),
    path('years/', views.AcademicYearListCreateView.as_view(), name='year_list_create'),
    path('levels/', views.LevelListCreateView.as_view(), name='level_list_create'),
    path('upload-students/', views.UploadStudentsView.as_view(), name='upload_students'),
    path('students/', views.list_students, name='list_students'),
    path('students/<int:pk>/manage/', views.manage_student, name='manage_student'),
    path('years/<int:pk>/', views.AcademicYearDetailView.as_view(), name='year_detail'),
    path('levels/<int:pk>/', views.LevelDetailView.as_view(), name='level_detail'),
    path('doctor/attendance/', views.ManageAttendanceView.as_view(), name='doctor_attendance'),
    path('upload-certificate/', views.UploadCertificateView.as_view(), name='upload_certificate'),
    path('my-certificate/', views.get_my_certificate, name='get_my_certificate'),
    path('profile/', views.get_user_profile, name='user_profile'),
    path('doctor/exams/', views.ManageExamsView.as_view(), name='doctor_exams'),
    path('doctor/exams/<int:pk>/delete/', views.delete_exam, name='delete_exam'),
    path('student/exams/', views.get_student_exams, name='student_exams'),
]